spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TrazabilidadCannabis?useSSL=false&serverTimezone=UTC
    username: root
    password: True*2025
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

      springdoc:
        api-docs:
          path: /v3/api-docs
        swagger-ui:
          path: /swagger-ui.html
          operationsSorter: method
          tagsSorter: alpha
          display-request-duration: true
        packages-to-scan: com.cruz.trazabilidadcannabis.controller

server:
  port: 8181