spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TrazabilidadCannabis?useSSL=false&serverTimezone=UTC
    username: root
    password: True*2025
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8181